brew "fzf"
brew "zsh-autosuggestions"
brew "carapace"
brew "fnm"
brew "direnv"
brew "starship"
brew "zoxide"
brew "thefuck"
brew "fastfetch"
brew "eza"
brew "chezmoi"
brew "delta"
brew "zsh-syntax-highlighting"
brew "fzf-tab"

cask "visual-studio-code"
cask "iterm2"
cask "obsidian"