command_timeout = 800

[sudo]
disabled = false

[git_metrics]
disabled = false

[status]
disabled = false

[shell]
disabled = false

[direnv]
disabled = false

# ~/.config/starship.toml

[cmd_duration]
min_time = 500
format = '[$duration](bold yellow)'

[custom.uv_python]
command = 'uv python find --show-version'
format = 'via [${symbol}(${output} )]($style)'
symbol = "uv "
detect_extensions = ['py', 'ipynb']
detect_files = ['.python-version', 'Pipfile', '__init__.py', 'pyproject.toml', 'requirements.txt', 'setup.py', 'tox.ini', 'uv.lock', 'pylock.toml']
style = "bold purple"
