command_timeout = 800

[sudo]
disabled = false

[git_metrics]
disabled = false

[status]
disabled = false

[shell]
disabled = false

[direnv]
disabled = false

# ~/.config/starship.toml

[cmd_duration]
min_time = 500
format = '[$duration](bold yellow)'
